using System.Collections.Immutable;

namespace Flow.Windows.Shell;

/// <summary>Provides the complete human-readable shell catalog for one supported language.</summary>
public sealed class FlowWindowsTextCatalog
{
    private static readonly ImmutableDictionary<string, string> English = CreateEnglish();
    private static readonly ImmutableDictionary<string, string> Portuguese = CreatePortuguese();
    private readonly ImmutableDictionary<string, string> _values;

    public FlowWindowsTextCatalog(string language)
    {
        Language = string.Equals(language, FlowWindowsSettings.PortugueseBrazil, StringComparison.OrdinalIgnoreCase)
            ? FlowWindowsSettings.PortugueseBrazil
            : FlowWindowsSettings.English;
        _values = Language == FlowWindowsSettings.PortugueseBrazil ? Portuguese : English;
    }

    public string Language { get; }

    public string this[string key] => _values.TryGetValue(key, out var value)
        ? value
        : throw new KeyNotFoundException($"Shell text '{key}' is not defined for {Language}.");

    public ImmutableArray<string> Keys => [.. _values.Keys];

    private static ImmutableDictionary<string, string> CreateEnglish() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["AppName"] = "Flow Engine .NET",
            ["WindowTitle"] = "Flow Engine .NET",
            ["NavHome"] = "Home",
            ["NavLibrary"] = "Personal folder",
            ["NavOperations"] = "Process a document",
            ["NavHowItWorks"] = "How it works",
            ["NavSettings"] = "Settings",
            ["NavigationName"] = "Main navigation",
            ["HomeTitle"] = "Work with semantic documents",
            ["HomeLead"] = "Flow separates a document's meaning from layout and rendering. This preview provides a local Windows interface for the engine.",
            ["CommonActions"] = "Common actions",
            ["InspectTitle"] = "Inspect an EPUB",
            ["InspectDescription"] = "Review publication structure and diagnostics without changing the original file.",
            ["ImportTitle"] = "Import to Flow",
            ["ImportDescription"] = "Create a semantic .flow.json document with stable identity and reading order.",
            ["ValidateTitle"] = "Validate a Flow document",
            ["ValidateDescription"] = "Check semantic structure, anchors, assets, notes, and table-of-contents targets.",
            ["ActionButton"] = "Open",
            ["ActionUnavailable"] = "Open the local document workflow.",
            ["PreviewAction"] = "Preview",
            ["LibraryTitle"] = "Personal book folder",
            ["LibraryLead"] = "Choose a local folder to discover EPUB files without moving, renaming, or modifying them. The index is rebuilt when needed and is not part of any Flow document.",
            ["LibraryNoFolder"] = "No personal folder selected",
            ["LibraryListName"] = "Local EPUB publications",
            ["LibraryChooseFolder"] = "Choose folder",
            ["LibraryRefresh"] = "Refresh",
            ["LibraryProgress"] = "Reviewed {0} of {1} publications…",
            ["LibraryComplete"] = "Found {0} local EPUB publications.",
            ["LibraryTruncated"] = "The list reached the safety limit of 500 EPUB files. Choose a smaller folder to review the remaining books.",
            ["LibraryCanceled"] = "Folder discovery was canceled.",
            ["LibraryUsable"] = "The publication can be processed by the current Flow subset.",
            ["LibraryNeedsReview"] = "This publication needs review. Open its diagnostics before importing it.",
            ["PreviewTitle"] = "Local renderer preview",
            ["PreviewNotice"] = "This is a restricted preview of the current HTML renderer. It is not pagination and is not the Flow Reader. Network navigation, downloads, permissions, and external resources are blocked.",
            ["PreviewPhone"] = "Phone",
            ["PreviewTablet"] = "Tablet",
            ["PreviewDesktop"] = "Desktop",
            ["PreviewReady"] = "The local preview is ready.",
            ["PreviewSurface"] = "Restricted local book preview",
            ["PreviewFailed"] = "The preview could not be generated.",
            ["PreviewBlockedNavigation"] = "External navigation was blocked by the preview.",
            ["PreviewBlockedDownload"] = "The preview blocked a download request.",
            ["AdvancedPanelTitle"] = "Advanced details",
            ["AdvancedPanelNotice"] = "The command below is for review or copying only. The application does not execute it. Saved logs may contain local paths and are created only where you choose.",
            ["CopyCommand"] = "Copy command",
            ["SaveLog"] = "Save log",
            ["OpenPowerShell"] = "Copy and open PowerShell",
            ["OperationsTitle"] = "Process a local document",
            ["OperationsLead"] = "Inspect or import an EPUB, or validate an EPUB or Flow document. Files and metadata stay on this device.",
            ["ChooseFile"] = "Choose a file",
            ["DropFile"] = "Drop a local .epub or .flow.json file here",
            ["SelectedFile"] = "Selected file",
            ["NoFileSelected"] = "No file selected",
            ["InspectAction"] = "Inspect EPUB",
            ["ImportAction"] = "Import to Flow",
            ["ValidateAction"] = "Validate document",
            ["OutputOptions"] = "Import options",
            ["OutputPath"] = "Flow document destination",
            ["DiagnosticsReport"] = "Save a diagnostics report",
            ["HtmlBook"] = "Generate an HTML book",
            ["HtmlLanguage"] = "Generated HTML interface language",
            ["LanguageAutomatic"] = "Automatic",
            ["LanguageEnglish"] = "English",
            ["LanguagePortugueseBrazil"] = "Portuguese (Brazil)",
            ["LanguagePortuguesePortugal"] = "Portuguese (Portugal)",
            ["RunAction"] = "Run",
            ["CancelAction"] = "Cancel",
            ["ProgressStarted"] = "Preparing the operation…",
            ["ProgressProcessing"] = "Reading the publication…",
            ["ProgressValidating"] = "Validating semantic content…",
            ["ProgressLayingOut"] = "Preparing adaptive layout…",
            ["ProgressRendering"] = "Generating the HTML book…",
            ["ProgressCompleted"] = "Operation completed.",
            ["ResultSuccess"] = "The operation completed successfully.",
            ["ResultFailure"] = "The operation completed with errors.",
            ["ResultCanceled"] = "The operation was canceled. No partial output was kept.",
            ["ResultUnexpected"] = "The operation could not be completed.",
            ["PublicationDetails"] = "Publication details",
            ["TitleLabel"] = "Title",
            ["AuthorsLabel"] = "Authors",
            ["LanguageValueLabel"] = "Language",
            ["EpubVersionLabel"] = "EPUB version",
            ["ResourcesLabel"] = "Resources",
            ["SpineLabel"] = "Reading-order items",
            ["AssetsLabel"] = "Imported assets",
            ["CoverLabel"] = "Publication cover",
            ["NoCover"] = "No safe cover is available for this result.",
            ["DiagnosticsTitle"] = "Diagnostics and technical details",
            ["NoDiagnostics"] = "No diagnostics were produced.",
            ["OutputCreated"] = "Created file",
            ["ConfirmReplaceTitle"] = "Replace existing output?",
            ["ConfirmReplaceText"] = "One or more destinations already exist. Flow will replace only the selected operation outputs.",
            ["ConfirmResumeTitle"] = "Resume interrupted operation?",
            ["ConfirmResumeText"] = "Flow found a recognized partial output. It will discard that partial data and run the operation again from the selected source.",
            ["ConfirmButton"] = "Continue",
            ["BackButton"] = "Go back",
            ["InvalidSelection"] = "Choose a local .epub or .flow.json file supported by this operation.",
            ["SourceReadOnlyNotice"] = "The selected source is opened read-only and is never overwritten.",
            ["HowTitle"] = "How Flow works",
            ["HowLead"] = "The document remains the same while a host adapts its presentation to a device and renderer.",
            ["DocumentTitle"] = "Document",
            ["DocumentDescription"] = "Canonical identity, metadata, semantic content, assets, and stable anchors.",
            ["LayoutTitle"] = "Layout",
            ["LayoutDescription"] = "Noncanonical reading decisions derived from the document, viewport, and user preferences.",
            ["RenderingTitle"] = "Rendering",
            ["RenderingDescription"] = "A concrete output such as standalone HTML or a navigable HTML book.",
            ["Invariant"] = "Document != Layout != Rendering",
            ["InvariantExplanation"] = "Fonts, themes, viewport size, and renderer choices do not change the canonical document hash.",
            ["WhyTitle"] = "Why this separation exists",
            ["WhyText"] = "A book should keep its identity when it moves between screens, reading preferences, or rendering technologies. Flow normalizes supported source content once and lets each host present it safely.",
            ["SettingsTitle"] = "Settings",
            ["SettingsLead"] = "These preferences affect only this local application and can be rebuilt at any time.",
            ["LanguageLabel"] = "Language",
            ["ThemeLabel"] = "Theme",
            ["ThemeSystem"] = "Use Windows setting",
            ["ThemeLight"] = "Light",
            ["ThemeDark"] = "Dark",
            ["AdvancedMode"] = "Advanced mode",
            ["AdvancedModeDescription"] = "Show technical identifiers, progress details, and equivalent commands on the operation page.",
            ["SettingsSaved"] = "Settings are saved on this device.",
        }.ToImmutableDictionary(StringComparer.Ordinal);

    private static ImmutableDictionary<string, string> CreatePortuguese() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["AppName"] = "Flow Engine .NET",
            ["WindowTitle"] = "Flow Engine .NET",
            ["NavHome"] = "Início",
            ["NavLibrary"] = "Pasta pessoal",
            ["NavOperations"] = "Processar documento",
            ["NavHowItWorks"] = "Como funciona",
            ["NavSettings"] = "Configurações",
            ["NavigationName"] = "Navegação principal",
            ["HomeTitle"] = "Trabalhe com documentos semânticos",
            ["HomeLead"] = "O Flow separa o significado do documento do layout e da renderização. Esta prévia oferece uma interface local para Windows sobre o motor.",
            ["CommonActions"] = "Ações comuns",
            ["InspectTitle"] = "Inspecionar um EPUB",
            ["InspectDescription"] = "Consulte a estrutura e os diagnósticos da publicação sem alterar o arquivo original.",
            ["ImportTitle"] = "Importar para Flow",
            ["ImportDescription"] = "Crie um documento semântico .flow.json com identidade estável e ordem de leitura preservada.",
            ["ValidateTitle"] = "Validar um documento Flow",
            ["ValidateDescription"] = "Verifique estrutura semântica, âncoras, assets, notas e destinos do sumário.",
            ["ActionButton"] = "Abrir",
            ["ActionUnavailable"] = "Abre o fluxo local de documentos.",
            ["PreviewAction"] = "Visualizar",
            ["LibraryTitle"] = "Pasta pessoal de livros",
            ["LibraryLead"] = "Escolha uma pasta local para encontrar arquivos EPUB sem mover, renomear ou modificar os livros. O índice é reconstruído quando necessário e não faz parte de nenhum documento Flow.",
            ["LibraryNoFolder"] = "Nenhuma pasta pessoal selecionada",
            ["LibraryListName"] = "Publicações EPUB locais",
            ["LibraryChooseFolder"] = "Escolher pasta",
            ["LibraryRefresh"] = "Atualizar",
            ["LibraryProgress"] = "Foram analisadas {0} de {1} publicações…",
            ["LibraryComplete"] = "Foram encontradas {0} publicações EPUB locais.",
            ["LibraryTruncated"] = "A lista atingiu o limite de segurança de 500 EPUBs. Escolha uma pasta menor para analisar os demais livros.",
            ["LibraryCanceled"] = "A busca na pasta foi cancelada.",
            ["LibraryUsable"] = "A publicação pode ser processada pelo subconjunto atual do Flow.",
            ["LibraryNeedsReview"] = "Esta publicação precisa de revisão. Consulte os diagnósticos antes de importá-la.",
            ["PreviewTitle"] = "Prévia local do renderer",
            ["PreviewNotice"] = "Esta é uma prévia restrita do renderer HTML atual. Não é paginação nem o Flow Reader. Navegação pela internet, downloads, permissões e recursos externos ficam bloqueados.",
            ["PreviewPhone"] = "Celular",
            ["PreviewTablet"] = "Tablet",
            ["PreviewDesktop"] = "Desktop",
            ["PreviewReady"] = "A prévia local está pronta.",
            ["PreviewSurface"] = "Prévia local e restrita do livro",
            ["PreviewFailed"] = "Não foi possível gerar a prévia.",
            ["PreviewBlockedNavigation"] = "A prévia bloqueou uma navegação externa.",
            ["PreviewBlockedDownload"] = "A prévia bloqueou uma tentativa de download.",
            ["AdvancedPanelTitle"] = "Detalhes avançados",
            ["AdvancedPanelNotice"] = "O comando abaixo serve apenas para consulta ou cópia. A aplicação não o executa. Logs salvos podem conter caminhos locais e só são criados no destino escolhido por você.",
            ["CopyCommand"] = "Copiar comando",
            ["SaveLog"] = "Salvar log",
            ["OpenPowerShell"] = "Copiar e abrir PowerShell",
            ["OperationsTitle"] = "Processar um documento local",
            ["OperationsLead"] = "Inspecione ou importe um EPUB, ou valide um EPUB ou documento Flow. Os arquivos e metadados permanecem neste dispositivo.",
            ["ChooseFile"] = "Escolher arquivo",
            ["DropFile"] = "Solte aqui um arquivo local .epub ou .flow.json",
            ["SelectedFile"] = "Arquivo selecionado",
            ["NoFileSelected"] = "Nenhum arquivo selecionado",
            ["InspectAction"] = "Inspecionar EPUB",
            ["ImportAction"] = "Importar para Flow",
            ["ValidateAction"] = "Validar documento",
            ["OutputOptions"] = "Opções de importação",
            ["OutputPath"] = "Destino do documento Flow",
            ["DiagnosticsReport"] = "Salvar relatório de diagnósticos",
            ["HtmlBook"] = "Gerar livro HTML",
            ["HtmlLanguage"] = "Idioma da interface gerada no HTML",
            ["LanguageAutomatic"] = "Automático",
            ["LanguageEnglish"] = "Inglês",
            ["LanguagePortugueseBrazil"] = "Português (Brasil)",
            ["LanguagePortuguesePortugal"] = "Português (Portugal)",
            ["RunAction"] = "Executar",
            ["CancelAction"] = "Cancelar",
            ["ProgressStarted"] = "Preparando a operação…",
            ["ProgressProcessing"] = "Lendo a publicação…",
            ["ProgressValidating"] = "Validando o conteúdo semântico…",
            ["ProgressLayingOut"] = "Preparando o layout adaptativo…",
            ["ProgressRendering"] = "Gerando o livro HTML…",
            ["ProgressCompleted"] = "Operação concluída.",
            ["ResultSuccess"] = "A operação foi concluída com sucesso.",
            ["ResultFailure"] = "A operação terminou com erros.",
            ["ResultCanceled"] = "A operação foi cancelada. Nenhuma saída parcial foi mantida.",
            ["ResultUnexpected"] = "Não foi possível concluir a operação.",
            ["PublicationDetails"] = "Dados da publicação",
            ["TitleLabel"] = "Título",
            ["AuthorsLabel"] = "Autores",
            ["LanguageValueLabel"] = "Idioma",
            ["EpubVersionLabel"] = "Versão do EPUB",
            ["ResourcesLabel"] = "Recursos",
            ["SpineLabel"] = "Itens na ordem de leitura",
            ["AssetsLabel"] = "Assets importados",
            ["CoverLabel"] = "Capa da publicação",
            ["NoCover"] = "Nenhuma capa segura está disponível neste resultado.",
            ["DiagnosticsTitle"] = "Diagnósticos e detalhes técnicos",
            ["NoDiagnostics"] = "Nenhum diagnóstico foi produzido.",
            ["OutputCreated"] = "Arquivo criado",
            ["ConfirmReplaceTitle"] = "Substituir a saída existente?",
            ["ConfirmReplaceText"] = "Um ou mais destinos já existem. O Flow substituirá somente as saídas desta operação.",
            ["ConfirmResumeTitle"] = "Retomar a operação interrompida?",
            ["ConfirmResumeText"] = "O Flow encontrou uma saída parcial reconhecida. Esses dados incompletos serão descartados e a operação recomeçará a partir da origem selecionada.",
            ["ConfirmButton"] = "Continuar",
            ["BackButton"] = "Voltar",
            ["InvalidSelection"] = "Escolha um arquivo local .epub ou .flow.json compatível com esta operação.",
            ["SourceReadOnlyNotice"] = "A origem selecionada é aberta somente para leitura e nunca será sobrescrita.",
            ["HowTitle"] = "Como o Flow funciona",
            ["HowLead"] = "O documento continua sendo o mesmo enquanto cada aplicação adapta sua apresentação ao dispositivo e ao renderer.",
            ["DocumentTitle"] = "Documento",
            ["DocumentDescription"] = "Identidade canônica, metadados, conteúdo semântico, assets e âncoras estáveis.",
            ["LayoutTitle"] = "Layout",
            ["LayoutDescription"] = "Decisões de leitura não canônicas derivadas do documento, da tela e das preferências do utilizador.",
            ["RenderingTitle"] = "Renderização",
            ["RenderingDescription"] = "Uma saída concreta, como HTML standalone ou um livro HTML navegável.",
            ["Invariant"] = "Documento != Layout != Renderização",
            ["InvariantExplanation"] = "Fonte, tema, tamanho da tela e escolha do renderer não alteram o hash canônico do documento.",
            ["WhyTitle"] = "Por que existe essa separação",
            ["WhyText"] = "Um livro deve manter sua identidade quando muda de tela, preferência de leitura ou tecnologia de renderização. O Flow normaliza o conteúdo suportado uma vez e permite que cada aplicação o apresente com segurança.",
            ["SettingsTitle"] = "Configurações",
            ["SettingsLead"] = "Estas preferências afetam somente esta aplicação local e podem ser reconstruídas a qualquer momento.",
            ["LanguageLabel"] = "Idioma",
            ["ThemeLabel"] = "Tema",
            ["ThemeSystem"] = "Usar configuração do Windows",
            ["ThemeLight"] = "Claro",
            ["ThemeDark"] = "Escuro",
            ["AdvancedMode"] = "Modo avançado",
            ["AdvancedModeDescription"] = "Mostra identificadores técnicos, detalhes do progresso e comandos equivalentes na página de operações.",
            ["SettingsSaved"] = "As configurações foram salvas neste dispositivo.",
        }.ToImmutableDictionary(StringComparer.Ordinal);
}
