namespace Flow.Cli;

internal enum CliPresentationMode
{
    Plain,
    Rich,
}

/// <summary>Describes presentation capabilities without changing command behavior or generated bytes.</summary>
internal sealed record CliPresentationProfile(
    CliPresentationMode Mode,
    bool IsInteractive,
    bool UseColor,
    int Width)
{
    public const int DefaultWidth = 80;

    public static CliPresentationProfile Plain() =>
        new(CliPresentationMode.Plain, IsInteractive: false, UseColor: false, DefaultWidth);
}

/// <summary>Selects a conservative presentation profile for the current invocation.</summary>
internal static class CliPresentationPolicy
{
    private const int MinimumWidth = 20;
    private const int MaximumWidth = 500;

    public static CliPresentationProfile Resolve(
        CliInvocationOptions invocation,
        IFlowTerminal terminal,
        TextWriter output,
        IEnvironmentVariables environment)
    {
        ArgumentNullException.ThrowIfNull(invocation);
        ArgumentNullException.ThrowIfNull(terminal);
        ArgumentNullException.ThrowIfNull(output);
        ArgumentNullException.ThrowIfNull(environment);

        try
        {
            var inputRedirected = terminal.IsInputRedirected;
            var outputRedirected = terminal.IsOutputRedirected;
            var ownsOutput = terminal.IsConsoleOutput(output);
            var supportsAnsi = terminal.SupportsAnsi;
            var width = terminal.GetWidth();
            if (width <= 0)
            {
                return CliPresentationProfile.Plain();
            }

            width = Math.Clamp(width, MinimumWidth, MaximumWidth);
            var interactive = !inputRedirected && !outputRedirected && ownsOutput;
            if (!interactive || !supportsAnsi)
            {
                return new CliPresentationProfile(
                    CliPresentationMode.Plain,
                    interactive,
                    UseColor: false,
                    width);
            }

            var noColor = invocation.NoColor || environment.Get("NO_COLOR") is not null;
            return new CliPresentationProfile(
                CliPresentationMode.Rich,
                IsInteractive: true,
                UseColor: !noColor,
                width);
        }
        catch (Exception exception) when (exception is IOException
                                          or InvalidOperationException
                                          or NotSupportedException
                                          or PlatformNotSupportedException
                                          or System.Security.SecurityException)
        {
            return CliPresentationProfile.Plain();
        }
    }
}
